-- Add additional profile fields
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS age INTEGER,
ADD COLUMN IF NOT EXISTS gender TEXT,
ADD COLUMN IF NOT EXISTS height NUMERIC,
ADD COLUMN IF NOT EXISTS height_unit TEXT DEFAULT 'inches',
ADD COLUMN IF NOT EXISTS weight NUMERIC,
ADD COLUMN IF NOT EXISTS weight_unit TEXT DEFAULT 'lbs',
ADD COLUMN IF NOT EXISTS target_weight NUMERIC,
ADD COLUMN IF NOT EXISTS target_weight_unit TEXT DEFAULT 'lbs',
ADD COLUMN IF NOT EXISTS goal TEXT DEFAULT 'leaner';